### ISSUE TITLE
Am I missing the details? Why should tree contain the node "CHILDREN", can we just make an array is children...?

### ISSUE THREAD

**Issue by HydTechie** [valor-software/ng2-tree#15]
Am I missing the details? Why should tree contain the node "CHILDREN", can we just make an array is children...? 

For: State has Cities (array) ; Each city has "restaurants" , again an array... display like a tree of states and cities within a State, Restaurants within a City... whats the need of "CHILDREN" node..how general is to get such API responses? 
Please help!

**Comment by rychkog** [comment]
You need to transform your structure to the one that satisfies `TreeModel` interface. 
Of course I could recursively scan object and in case if one of the properties is an array then treat it as children. But what if two properties are of type array? Also it adds redundant complexity to implementation. Interface is a contract and a point of extension that client should implement in order to conform to this contract.
