### ISSUE TITLE
Error "Please add a @NgModule annotation"

### ISSUE THREAD

**Issue by slay22** [valor-software/ng2-tree#164]
I have an Hybrid Angular App which i'm trying to upgrade and the idea it's to use already "upgraded"/"ported" components (ui-tree and ui-select are in use in the angularjs Part). I've created a new module in order to build new components (in this case using the ng-tree) to fit the design and unfortunately become the following error. 

![image](https://user-images.githubusercontent.com/443027/32950320-39e0a71a-cba6-11e7-92da-38a8c7aebb14.png)

Not using ng cli but using webpack directly to build. Maybe the problem its on the bundling configuration?.

Already checked on Angular Repository but the related Issues doesn't seem to fit this Problem. 

Many Thanks in Advance for the Help.

**Comment by rychkog** [comment]
@slay22 Which version of Angular do you use?

**Comment by slay22** [comment]
4,4.6. Sorry that I forgot it.

**Comment by rychkog** [comment]
@slay22 I'm already working on it. But because Angular 5 is not compatible with Angular 4. I can propose just two options:
1) Use ng2-tree v2.0.0-alpha.10
2) Wait a bit until I release v2.0.0-rc.2 but in this case, you still have to migrate your app to Angular 5.

You can use this tool, released by Angular team that makes upgrade process easier
https://angular-update-guide.firebaseapp.com/

**Comment by rychkog** [comment]
@slay22 
Try to use ng2-tree@2.0.0-rc.2
typescript 2.4.2

**Comment by slay22** [comment]
Many Thanks for the Answer, I will try with the rc.2 and also try to migrate/upgrade to 5 and if it works we can close the issue, I'll let you know.
