### ISSUE TITLE
How can i disable or hide specific context menu items?

### ISSUE THREAD

**Issue by KhizarJaved** [valor-software/ng2-tree#53]

**Comment by rychkog** [comment]
@KhizarJaved Currently it is impossible to disable or hide particular context menu items. It is pain - I know. I'll work on this once `children async loading` is finished (for this to be done I need to add couple tests)

**Comment by bebeto84** [comment]
Which is the current status of this feature? Will be implemented any time soon?

**Comment by aldari** [comment]
Hello, I offer to add an opportunity to hide the whole menu in settings. I think it is easier to implement. We have onSelect event and can create sidebar instead of menu. The menu item handlers broke whole ui logic.
Adding settings allow to have one package for demo on this site and for current usage in production.

**Comment by rychkog** [comment]
@aldari Can you elaborate on this and provide some examples?
