### ISSUE TITLE
Base Tree node image on bound data

### ISSUE THREAD

**Issue by dekenless** [valor-software/ng2-tree#85]
How would one go about displaying an image for the tree node based on an object set for the Value of the TreeModel?

**Comment by rychkog** [comment]
@dekenless Latest development version correctly renders html if it is present in the value of the TreeModel. 
So from what I see - you can create a TreeModel with an `img` as a value and it will be rendered.

You can use develop branch in your package.json or wait for the new version's release in order to take advantage of this.

**Comment by dekenless** [comment]
Thanks, but If my Value is say a class with for example a name, id and an image, and implements RenamableNode what then? If in my implementation of toString() can I simply return html where I specify the image and say node text?

**Comment by rychkog** [comment]
@dekenless Yes, I think if your RenamableNode's toString will return html it should be rendered correctly (but this functionality is available only in the develop branch of the ng2-tree - not released yet)

**Comment by rychkog** [comment]
@dekenless Already released on npm - give it a try
